[package]
name = "advent"
version = "0.1.0"
authors = ["James Kominick <james@kominick.com>"]

[dependencies]
log = "0.4"
env_logger = "0.5"
chrono = "0.4"
regex = "1"
lazy_static = "1"
itertools = "0.7"
